local NCC = select(2, ...)
local L = NCC.L

L["addon.name"] = "Native Chat Channels"
L["settings.subtitle"] = "Configure behavior and appearance of channel buttons."
L["settings.reset_defaults"] = "Reset Defaults"

L["settings.general.enable.label"] = "Enable addon"
L["settings.general.enable.tooltip"] = "Master enable."
L["settings.general.only_joined.label"] = "Show only joined custom channels"
L["settings.general.only_joined.tooltip"] = "Filter buttons that are not joined."
L["settings.general.tab.header"] = "Tab"
L["settings.general.tab_cycle.label"] = "Enable Tab channel cycling"
L["settings.general.tab_cycle.tooltip"] = "Cycles SAY -> PARTY -> INSTANCE -> GUILD."

L["settings.text.mode.label"] = "Label mode"
L["settings.text.mode.short"] = "Short"
L["settings.text.mode.full"] = "Full"
L["settings.text.mode.custom"] = "Custom"
L["settings.text.custom_labels.header"] = "Custom labels"
L["settings.text.font.label"] = "Font"
L["settings.text.font.hint"] = "For more font choices, install SharedMedia and SharedMediaAdditionalFonts."
L["settings.text.size.label"] = "Text size"
L["settings.text.outline.label"] = "Text outline"
L["settings.text.outline.tooltip"] = "Outline for better readability."

L["settings.buttons.size.label"] = "Button size"
L["settings.buttons.spacing.label"] = "Spacing"
L["settings.buttons.style.label"] = "Style"
L["settings.buttons.style.flat"] = "Flat"
L["settings.buttons.style.textured"] = "Textured"
L["settings.buttons.bg_texture.label"] = "Background texture"
L["settings.buttons.corner.label"] = "Corner amount"
L["settings.buttons.bg_alpha.label"] = "Background alpha"
L["settings.buttons.border_alpha.label"] = "Border alpha"
L["settings.buttons.border_thickness.label"] = "Border thickness"

L["settings.channels.say.label"] = "Say"
L["settings.channels.say.tooltip"] = "Show/hide SAY button."
L["settings.channels.party.label"] = "Party"
L["settings.channels.party.tooltip"] = "Show/hide PARTY button."
L["settings.channels.instance.label"] = "Dungeon/Instance"
L["settings.channels.instance.tooltip"] = "Show/hide INSTANCE button."
L["settings.channels.guild.label"] = "Guild"
L["settings.channels.guild.tooltip"] = "Show/hide GUILD button."
L["settings.channels.raid.label"] = "Raid"
L["settings.channels.raid.tooltip"] = "Show/hide RAID button."
L["settings.channels.officer.label"] = "Officer"
L["settings.channels.officer.tooltip"] = "Show/hide OFFICER button."
L["settings.channels.yell.label"] = "Yell"
L["settings.channels.yell.tooltip"] = "Show/hide YELL button."
L["settings.channels.emote.label"] = "Emote"
L["settings.channels.emote.tooltip"] = "Show/hide EMOTE button."
L["settings.channels.whisper.label"] = "Whisper"
L["settings.channels.whisper.tooltip"] = "Show/hide WHISPER button."
L["settings.channels.ch1.label"] = "Channel 1 (CH:1)"
L["settings.channels.ch1.tooltip"] = "Show/hide CH:1 button."
L["settings.channels.ch2.label"] = "Channel 2 (CH:2)"
L["settings.channels.ch2.tooltip"] = "Show/hide CH:2 button."

L["settings.tabs.general"] = "General"
L["settings.tabs.text"] = "Text"
L["settings.tabs.buttons"] = "Buttons"
L["settings.tabs.channels"] = "Channels"

L["settings.custom_label.say"] = "SAY name"
L["settings.custom_label.party"] = "PARTY name"
L["settings.custom_label.raid"] = "RAID name"
L["settings.custom_label.instance"] = "INSTANCE name"
L["settings.custom_label.guild"] = "GUILD name"
L["settings.custom_label.officer"] = "OFFICER name"
L["settings.custom_label.yell"] = "YELL name"
L["settings.custom_label.emote"] = "EMOTE name"
L["settings.custom_label.whisper"] = "WHISPER name"
L["settings.custom_label.ch1"] = "CH:1 name"
L["settings.custom_label.ch2"] = "CH:2 name"

L["tooltip.channel_mode"] = "Channel: %s"
L["tooltip.channel_whisper_last"] = "Channel: WHISPER (last)"
L["tooltip.channel_number_name"] = "Channel: %d. %s"
L["tooltip.channel_number"] = "Channel: %d"

L["channel.mode.SAY"] = "SAY"
L["channel.mode.YELL"] = "YELL"
L["channel.mode.EMOTE"] = "EMOTE"
L["channel.mode.PARTY"] = "PARTY"
L["channel.mode.RAID"] = "RAID"
L["channel.mode.INSTANCE"] = "INSTANCE"
L["channel.mode.GUILD"] = "GUILD"
L["channel.mode.OFFICER"] = "OFFICER"
L["channel.mode.WHISPER"] = "WHISPER"

L["msg.settings_reset"] = "NativeChatChannels: settings reset to defaults."
L["msg.rebuilt"] = "NativeChatChannels: rebuilt."
L["msg.cannot_open_settings"] = "NativeChatChannels: cannot open settings on this client."
