local NCC = select(2, ...)
local L = NCC.L

if GetLocale() ~= "ruRU" then return end

L["addon.name"] = "Native Chat Channels"
L["settings.subtitle"] = "Настройка поведения и внешнего вида кнопок каналов."
L["settings.reset_defaults"] = "Сбросить настройки"

L["settings.general.enable.label"] = "Включить аддон"
L["settings.general.enable.tooltip"] = "Главный переключатель."
L["settings.general.only_joined.label"] = "Показывать только подключённые каналы"
L["settings.general.only_joined.tooltip"] = "Скрывает кнопки для не подключённых каналов."
L["settings.general.tab.header"] = "Tab"
L["settings.general.tab_cycle.label"] = "Включить переключение каналов по Tab"
L["settings.general.tab_cycle.tooltip"] = "Цикл: Сказать -> Группа -> Подземелье -> Гильдия."

L["settings.text.mode.label"] = "Режим подписи"
L["settings.text.mode.short"] = "Короткий"
L["settings.text.mode.full"] = "Полный"
L["settings.text.mode.custom"] = "Свой"
L["settings.text.custom_labels.header"] = "Свои подписи"
L["settings.text.font.label"] = "Шрифт"
L["settings.text.font.hint"] = "Для большего выбора шрифтов установите SharedMedia и SharedMediaAdditionalFonts."
L["settings.text.size.label"] = "Размер текста"
L["settings.text.outline.label"] = "Обводка текста"
L["settings.text.outline.tooltip"] = "Обводка для лучшей читаемости."

L["settings.buttons.size.label"] = "Размер кнопок"
L["settings.buttons.spacing.label"] = "Отступ"
L["settings.buttons.style.label"] = "Стиль"
L["settings.buttons.style.flat"] = "Плоский"
L["settings.buttons.style.textured"] = "Текстурный"
L["settings.buttons.bg_texture.label"] = "Текстура фона"
L["settings.buttons.corner.label"] = "Скругление"
L["settings.buttons.bg_alpha.label"] = "Прозрачность фона"
L["settings.buttons.border_alpha.label"] = "Прозрачность рамки"
L["settings.buttons.border_thickness.label"] = "Толщина рамки"

L["settings.channels.say.label"] = "Сказать"
L["settings.channels.say.tooltip"] = "Показать/скрыть кнопку «Сказать»."
L["settings.channels.party.label"] = "Группа"
L["settings.channels.party.tooltip"] = "Показать/скрыть кнопку «Группа»."
L["settings.channels.instance.label"] = "Подземелье/Инстанс"
L["settings.channels.instance.tooltip"] = "Показать/скрыть кнопку «Подземелье»."
L["settings.channels.guild.label"] = "Гильдия"
L["settings.channels.guild.tooltip"] = "Показать/скрыть кнопку «Гильдия»."
L["settings.channels.raid.label"] = "Рейд"
L["settings.channels.raid.tooltip"] = "Показать/скрыть кнопку «Рейд»."
L["settings.channels.officer.label"] = "Офицерский"
L["settings.channels.officer.tooltip"] = "Показать/скрыть кнопку «Офицерский»."
L["settings.channels.yell.label"] = "Крик"
L["settings.channels.yell.tooltip"] = "Показать/скрыть кнопку «Крик»."
L["settings.channels.emote.label"] = "Эмоция"
L["settings.channels.emote.tooltip"] = "Показать/скрыть кнопку «Эмоция»."
L["settings.channels.whisper.label"] = "Шёпот"
L["settings.channels.whisper.tooltip"] = "Показать/скрыть кнопку «Шёпот»."
L["settings.channels.ch1.label"] = "Канал 1 (CH:1)"
L["settings.channels.ch1.tooltip"] = "Показать/скрыть кнопку CH:1."
L["settings.channels.ch2.label"] = "Канал 2 (CH:2)"
L["settings.channels.ch2.tooltip"] = "Показать/скрыть кнопку CH:2."

L["settings.tabs.general"] = "Общие"
L["settings.tabs.text"] = "Текст"
L["settings.tabs.buttons"] = "Кнопки"
L["settings.tabs.channels"] = "Каналы"

L["settings.custom_label.say"] = "Название Сказать"
L["settings.custom_label.party"] = "Название Группа"
L["settings.custom_label.raid"] = "Название Рейд"
L["settings.custom_label.instance"] = "Название Подземелье"
L["settings.custom_label.guild"] = "Название Гильдия"
L["settings.custom_label.officer"] = "Название Офицерский"
L["settings.custom_label.yell"] = "Название Крик"
L["settings.custom_label.emote"] = "Название Эмоция"
L["settings.custom_label.whisper"] = "Название Шёпот"
L["settings.custom_label.ch1"] = "Название CH:1"
L["settings.custom_label.ch2"] = "Название CH:2"

L["tooltip.channel_mode"] = "Канал: %s"
L["tooltip.channel_whisper_last"] = "Канал: Шёпот (последний)"
L["tooltip.channel_number_name"] = "Канал: %d. %s"
L["tooltip.channel_number"] = "Канал: %d"

L["channel.mode.SAY"] = "Сказать"
L["channel.mode.YELL"] = "Крик"
L["channel.mode.EMOTE"] = "Эмоция"
L["channel.mode.PARTY"] = "Группа"
L["channel.mode.RAID"] = "Рейд"
L["channel.mode.INSTANCE"] = "Подземелье"
L["channel.mode.GUILD"] = "Гильдия"
L["channel.mode.OFFICER"] = "Офицерский"
L["channel.mode.WHISPER"] = "Шёпот"

L["msg.settings_reset"] = "NativeChatChannels: настройки сброшены по умолчанию."
L["msg.rebuilt"] = "NativeChatChannels: панель пересобрана."
L["msg.cannot_open_settings"] = "NativeChatChannels: не удалось открыть настройки на этом клиенте."
